const Path = {
  signin: '/auth/sign-in',
  signinV2: '/auth/sign-in-v2',
  login: '/auth/login',
  signup: '/auth/sign-up',
  signupV2: '/auth/sign-up-v2',
  registration: '/auth/register',
  signupSuccess: '/auth/sign-up/success',
  checkEmail: '/auth/verify-email-confirmation',
  verifyEmail: '/auth/verify-email/:email',
  verificationLinkExpired: '/auth/verification-link-expired',
  forgotPassword: '/auth/recovery/forgot-password',
  resetPassword: '/auth/recovery/reset-password',
  setNewPassword: '/auth/recovery/set-new-password/:email',
  passwordResetSuccess: '/auth/recovery/password-reset-success',
  registrationSuccess: '/auth/registration-success',
  emailVerification: '/auth/verification/email-sent',
  emailVerifiedSuccess: '/auth/verify-email/success',
  requestEmailChange: '/auth/email/request-change',
  initiateEmailChange: '/auth/email/initiate-change',
  emailChangeVerificationPending: '/auth/email/change-verification-pending',
  emailChangeVerification: '/auth/email/verify-change/:token',
  emailChangeSuccess: '/auth/email/change-success',
  emailChangeFailed: '/auth/email/change-failed',
  emailChangeStatus: '/auth/email/change-status',
  mfaVerification: '/auth/mfa/verification',
  exportVerification: '/auth/export/verification',
  deviceCode: '/auth/device/code',
  adminLogin: '/auth/admin/login',
  joinOrganization: '/auth/join-organization',
  // System & Error Paths
  unauthorized401: '/auth/401',
  maintenance: '/auth/maintenance',
  tooManyRequests429: '/auth/429',
  csrfError: '/auth/csrf-error',
  browserNotSupported: '/auth/browser-unsupported',
  forbidden403: '/auth/403',
}
export default Path
