export const menuClasses = {
  root: 'menu-root',
  menuItem: 'menu-item',
  menuItemRoot: 'menu-item-root',
  subMenuRoot: 'submenu-root',
  button: 'menu-button',
  content: 'menu-content',
  label: 'menu-label',
  prefix: 'menu-prefix',
  suffix: 'menu-suffix',
  icon: 'menu-icon',
  subMenuContent: 'submenu-content',
  subMenuExpandIcon: 'submenu-expand-icon',
  menuSectionRoot: 'menu-section-root',
  menuSectionContent: 'menu-section-content',
  menuSectionLabel: 'menu-section-label',
  menuSectionWrapper: 'menu-section-wrapper',
  disabled: 'disabled',
  active: 'active',
  open: 'open',
} as const

export const verticalNavClasses = {
  root: 'vertical-nav-root',
  container: 'vertical-nav-container',
  header: 'vertical-nav-header',
  content: 'vertical-nav-content',
  overlay: 'vertical-nav-overlay',
  backdrop: 'vertical-nav-backdrop',
  bgColorContainer: 'vertical-nav-bg-color-container',
  icon: 'vertical-nav-icon',
  image: 'vertical-nav-image',
  toggled: 'toggled',
  collapsed: 'collapsed',
  collapsing: 'collapsing',
  expanding: 'expanding',
  hovered: 'hovered',
  scrollWithContent: 'scroll-with-content',
  breakpointReached: 'breakpoint-reached',
} as const

export const horizontalNavClasses = {
  root: 'horizontal-nav-root',
  container: 'horizontal-nav-container',
  menu: 'horizontal-nav-menu',
  menuItem: 'horizontal-nav-menu-item',
  subMenu: 'horizontal-nav-submenu',
  subMenuContent: 'horizontal-nav-submenu-content',
  active: 'active',
  open: 'open',
  disabled: 'disabled',
} as const
