import React, { useState, useCallback, useRef, useEffect } from 'react'
import {
  Box,
  Paper,
  Typography,
  Stack,
  TextField,
  IconButton,
  Divider,
  CircularProgress,
  Fade,
} from '@mui/material'
import SendRounded from '@mui/icons-material/SendRounded'
import SmartToyRounded from '@mui/icons-material/SmartToyRounded'
import PersonRounded from '@mui/icons-material/PersonRounded'
import { useTranslation } from 'react-i18next'
import { apiClient } from '@cap/platform-core'

interface Message {
  id: string
  role: 'user' | 'assistant'
  content: string
  timestamp: Date
}

/**
 * AiChatWidget — A conversational AI chat interface embedded in the dashboard.
 *
 * Messages are relayed through the backend AI endpoint (`POST /api/v1/ai/chat`)
 * using the authenticated session cookie. No AI provider API key is ever exposed
 * to the browser.
 *
 * Registered as 'dashboard-widget-aiChat' in the widget registry.
 * Can be generated by the AI Widget Studio pipeline.
 */
const AiChatWidget: React.FC = () => {
  const { t } = useTranslation()
  const [messages, setMessages] = useState<Message[]>([
    {
      id: 'welcome',
      role: 'assistant',
      content: t('dashboard.widgets.aiChat.welcome', 'Hello! I\'m your AI assistant. How can I help you today?'),
      timestamp: new Date(),
    },
  ])
  const [input, setInput] = useState('')
  const [isLoading, setIsLoading] = useState(false)
  const messagesEndRef = useRef<HTMLDivElement>(null)

  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' })
  }, [messages])

  const sendMessage = useCallback(async () => {
    const trimmed = input.trim()
    if (!trimmed || isLoading) return

    const userMsg: Message = {
      id: crypto.randomUUID(),
      role: 'user',
      content: trimmed,
      timestamp: new Date(),
    }

    setMessages((prev) => [...prev, userMsg])
    setInput('')
    setIsLoading(true)

    const assistantMsgId = crypto.randomUUID()
    setMessages((prev) => [
      ...prev,
      { id: assistantMsgId, role: 'assistant', content: '', timestamp: new Date() },
    ])

    try {
      // Relay through the backend AI endpoint. The provider API key stays on the
      // server; the browser only sends the authenticated session cookie.
      const { data } = await apiClient.post<{ reply?: string; message?: string; content?: string }>(
        '/api/v1/ai/chat',
        {
          message: trimmed,
          history: messages
            .filter((m) => m.id !== 'welcome')
            .map((m) => ({ role: m.role, content: m.content })),
        },
      )

      const reply =
        data?.reply ??
        data?.message ??
        data?.content ??
        t('dashboard.widgets.aiChat.noReply', 'No response was returned.')

      setMessages((prev) =>
        prev.map((m) => (m.id === assistantMsgId ? { ...m, content: reply } : m)),
      )
    } catch {
      setMessages((prev) =>
        prev.map((m) =>
          m.id === assistantMsgId
            ? {
                ...m,
                content: t(
                  'dashboard.widgets.aiChat.error',
                  'The assistant is unavailable right now. Please try again later.',
                ),
              }
            : m,
        ),
      )
    } finally {
      setIsLoading(false)
    }
  }, [input, isLoading, messages, t])

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault()
      sendMessage()
    }
  }

  return (
    <Paper
      variant="outlined"
      sx={{
        p: 0,
        height: '100%',
        display: 'flex',
        flexDirection: 'column',
        minHeight: 280,
        overflow: 'hidden',
      }}
    >
      {/* Header */}
      <Box
        sx={{
          px: 2,
          py: 1.25,
          borderBottom: '1px solid',
          borderColor: 'divider',
          background: (theme) =>
            `linear-gradient(135deg, ${theme.palette.primary.main}12, ${theme.palette.secondary.main}08)`,
        }}
      >
        <Stack direction="row" spacing={1} alignItems="center">
          <SmartToyRounded color="primary" sx={{ fontSize: 20 }} />
          <Typography variant="subtitle2" fontWeight={700}>
            {t('dashboard.widgets.aiChat.title', 'AI Assistant')}
          </Typography>
        </Stack>
      </Box>

      {/* Messages */}
      <Box sx={{ flex: 1, overflow: 'auto', p: 1.5, display: 'flex', flexDirection: 'column', gap: 1 }}>
        {messages.map((msg) => (
          <Fade key={msg.id} in>
            <Stack
              direction="row"
              spacing={1}
              alignItems="flex-start"
              justifyContent={msg.role === 'user' ? 'flex-end' : 'flex-start'}
            >
              {msg.role === 'assistant' && (
                <Box
                  sx={{
                    width: 24,
                    height: 24,
                    borderRadius: 1,
                    bgcolor: 'primary.main',
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    flexShrink: 0,
                    mt: 0.25,
                  }}
                >
                  <SmartToyRounded sx={{ fontSize: 14, color: 'white' }} />
                </Box>
              )}
              <Box
                sx={{
                  maxWidth: '80%',
                  px: 1.5,
                  py: 1,
                  borderRadius: msg.role === 'user' ? '12px 12px 2px 12px' : '2px 12px 12px 12px',
                  bgcolor: msg.role === 'user' ? 'primary.main' : 'background.default',
                  color: msg.role === 'user' ? 'primary.contrastText' : 'text.primary',
                  border: '1px solid',
                  borderColor: msg.role === 'user' ? 'primary.dark' : 'divider',
                }}
              >
                <Typography variant="caption" sx={{ lineHeight: 1.5, whiteSpace: 'pre-wrap' }}>
                  {msg.content || (
                    <Box sx={{ display: 'flex', gap: 0.5, alignItems: 'center' }}>
                      {[0, 1, 2].map((i) => (
                        <Box
                          key={i}
                          sx={{
                            width: 4,
                            height: 4,
                            borderRadius: '50%',
                            bgcolor: 'text.secondary',
                            animation: `bounce 0.6s ${i * 0.15}s ease infinite alternate`,
                            '@keyframes bounce': { from: { transform: 'translateY(0)' }, to: { transform: 'translateY(-4px)' } },
                          }}
                        />
                      ))}
                    </Box>
                  )}
                </Typography>
              </Box>
              {msg.role === 'user' && (
                <Box
                  sx={{
                    width: 24,
                    height: 24,
                    borderRadius: 1,
                    bgcolor: 'text.secondary',
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    flexShrink: 0,
                    mt: 0.25,
                  }}
                >
                  <PersonRounded sx={{ fontSize: 14, color: 'white' }} />
                </Box>
              )}
            </Stack>
          </Fade>
        ))}
        <div ref={messagesEndRef} />
      </Box>

      <Divider />

      {/* Input */}
      <Box sx={{ p: 1.25, display: 'flex', gap: 1, alignItems: 'flex-end' }}>
        <TextField
          multiline
          maxRows={2}
          fullWidth
          size="small"
          placeholder={t('dashboard.widgets.aiChat.placeholder', 'Ask me anything…')}
          value={input}
          onChange={(e) => setInput(e.target.value)}
          onKeyDown={handleKeyDown}
          disabled={isLoading}
          id="ai-chat-widget-input"
          sx={{
            '& .MuiOutlinedInput-root': { borderRadius: 1.5, fontSize: '0.8rem' },
          }}
        />
        <IconButton
          id="ai-chat-widget-send"
          size="small"
          onClick={sendMessage}
          disabled={!input.trim() || isLoading}
          color="primary"
          sx={{
            bgcolor: 'primary.main',
            color: 'white',
            borderRadius: 1.5,
            width: 34,
            height: 34,
            flexShrink: 0,
            '&:hover': { bgcolor: 'primary.dark' },
            '&.Mui-disabled': { bgcolor: 'action.disabledBackground' },
          }}
        >
          {isLoading ? <CircularProgress size={14} color="inherit" /> : <SendRounded sx={{ fontSize: 16 }} />}
        </IconButton>
      </Box>
    </Paper>
  )
}

export default AiChatWidget
