import React, { useState, useCallback, useRef, useEffect } from 'react'
import {
  Box,
  Paper,
  Typography,
  Stack,
  TextField,
  IconButton,
  Divider,
  CircularProgress,
  Fade,
} from '@mui/material'
import SendRounded from '@mui/icons-material/SendRounded'
import SmartToyRounded from '@mui/icons-material/SmartToyRounded'
import PersonRounded from '@mui/icons-material/PersonRounded'
import { useTranslation } from 'react-i18next'

interface Message {
  id: string
  role: 'user' | 'assistant'
  content: string
  timestamp: Date
}

/**
 * AiChatWidget — A conversational AI chat interface embedded in the dashboard.
 *
 * In Phase 1 this widget uses the VITE_GEMINI_API_KEY from the environment.
 * Messages are sent to Gemini and streamed back in real time.
 *
 * Registered as 'dashboard-widget-aiChat' in the widget registry.
 * Can be generated by the AI Widget Studio pipeline.
 */
const AiChatWidget: React.FC = () => {
  const { t } = useTranslation()
  const [messages, setMessages] = useState<Message[]>([
    {
      id: 'welcome',
      role: 'assistant',
      content: t('dashboard.widgets.aiChat.welcome', 'Hello! I\'m your AI assistant. How can I help you today?'),
      timestamp: new Date(),
    },
  ])
  const [input, setInput] = useState('')
  const [isLoading, setIsLoading] = useState(false)
  const messagesEndRef = useRef<HTMLDivElement>(null)

  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' })
  }, [messages])

  const sendMessage = useCallback(async () => {
    const trimmed = input.trim()
    if (!trimmed || isLoading) return

    const userMsg: Message = {
      id: crypto.randomUUID(),
      role: 'user',
      content: trimmed,
      timestamp: new Date(),
    }

    setMessages((prev) => [...prev, userMsg])
    setInput('')
    setIsLoading(true)

    const apiKey = (import.meta as ImportMeta & { env: Record<string, string | undefined> }).env
      .VITE_GEMINI_API_KEY

    if (!apiKey) {
      setMessages((prev) => [
        ...prev,
        {
          id: crypto.randomUUID(),
          role: 'assistant',
          content: '⚠️ VITE_GEMINI_API_KEY is not configured. Add it to your .env file to enable AI responses.',
          timestamp: new Date(),
        },
      ])
      setIsLoading(false)
      return
    }

    // Streaming Gemini call
    const model = (import.meta as ImportMeta & { env: Record<string, string | undefined> }).env
      .VITE_GEMINI_MODEL ?? 'gemini-2.0-flash'

    const assistantMsgId = crypto.randomUUID()
    setMessages((prev) => [
      ...prev,
      { id: assistantMsgId, role: 'assistant', content: '', timestamp: new Date() },
    ])

    try {
      const response = await fetch(
        `https://generativelanguage.googleapis.com/v1beta/models/${model}:streamGenerateContent?key=${apiKey}&alt=sse`,
        {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            system_instruction: {
              parts: [{
                text: 'You are a helpful dashboard assistant. Be concise and friendly. Keep responses under 200 words unless the user asks for more detail.',
              }],
            },
            contents: [{ role: 'user', parts: [{ text: trimmed }] }],
            generationConfig: { temperature: 0.7, maxOutputTokens: 512 },
          }),
        },
      )

      const reader = response.body?.getReader()
      const decoder = new TextDecoder()

      if (!reader) throw new Error('No response body')

      while (true) {
        const { done, value } = await reader.read()
        if (done) break

        const lines = decoder.decode(value, { stream: true }).split('\n')
        for (const line of lines) {
          if (!line.startsWith('data: ')) continue
          const jsonStr = line.slice(6).trim()
          if (jsonStr === '[DONE]') break
          try {
            const parsed = JSON.parse(jsonStr)
            const text: string = parsed?.candidates?.[0]?.content?.parts?.[0]?.text ?? ''
            if (text) {
              setMessages((prev) =>
                prev.map((m) =>
                  m.id === assistantMsgId ? { ...m, content: m.content + text } : m,
                ),
              )
            }
          } catch { /* skip non-JSON lines */ }
        }
      }
    } catch (err: unknown) {
      setMessages((prev) =>
        prev.map((m) =>
          m.id === assistantMsgId
            ? { ...m, content: `Error: ${err instanceof Error ? err.message : String(err)}` }
            : m,
        ),
      )
    } finally {
      setIsLoading(false)
    }
  }, [input, isLoading])

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault()
      sendMessage()
    }
  }

  return (
    <Paper
      variant="outlined"
      sx={{
        p: 0,
        height: '100%',
        display: 'flex',
        flexDirection: 'column',
        minHeight: 280,
        overflow: 'hidden',
      }}
    >
      {/* Header */}
      <Box
        sx={{
          px: 2,
          py: 1.25,
          borderBottom: '1px solid',
          borderColor: 'divider',
          background: (theme) =>
            `linear-gradient(135deg, ${theme.palette.primary.main}12, ${theme.palette.secondary.main}08)`,
        }}
      >
        <Stack direction="row" spacing={1} alignItems="center">
          <SmartToyRounded color="primary" sx={{ fontSize: 20 }} />
          <Typography variant="subtitle2" fontWeight={700}>
            {t('dashboard.widgets.aiChat.title', 'AI Assistant')}
          </Typography>
        </Stack>
      </Box>

      {/* Messages */}
      <Box sx={{ flex: 1, overflow: 'auto', p: 1.5, display: 'flex', flexDirection: 'column', gap: 1 }}>
        {messages.map((msg) => (
          <Fade key={msg.id} in>
            <Stack
              direction="row"
              spacing={1}
              alignItems="flex-start"
              justifyContent={msg.role === 'user' ? 'flex-end' : 'flex-start'}
            >
              {msg.role === 'assistant' && (
                <Box
                  sx={{
                    width: 24,
                    height: 24,
                    borderRadius: 1,
                    bgcolor: 'primary.main',
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    flexShrink: 0,
                    mt: 0.25,
                  }}
                >
                  <SmartToyRounded sx={{ fontSize: 14, color: 'white' }} />
                </Box>
              )}
              <Box
                sx={{
                  maxWidth: '80%',
                  px: 1.5,
                  py: 1,
                  borderRadius: msg.role === 'user' ? '12px 12px 2px 12px' : '2px 12px 12px 12px',
                  bgcolor: msg.role === 'user' ? 'primary.main' : 'background.default',
                  color: msg.role === 'user' ? 'primary.contrastText' : 'text.primary',
                  border: '1px solid',
                  borderColor: msg.role === 'user' ? 'primary.dark' : 'divider',
                }}
              >
                <Typography variant="caption" sx={{ lineHeight: 1.5, whiteSpace: 'pre-wrap' }}>
                  {msg.content || (
                    <Box sx={{ display: 'flex', gap: 0.5, alignItems: 'center' }}>
                      {[0, 1, 2].map((i) => (
                        <Box
                          key={i}
                          sx={{
                            width: 4,
                            height: 4,
                            borderRadius: '50%',
                            bgcolor: 'text.secondary',
                            animation: `bounce 0.6s ${i * 0.15}s ease infinite alternate`,
                            '@keyframes bounce': { from: { transform: 'translateY(0)' }, to: { transform: 'translateY(-4px)' } },
                          }}
                        />
                      ))}
                    </Box>
                  )}
                </Typography>
              </Box>
              {msg.role === 'user' && (
                <Box
                  sx={{
                    width: 24,
                    height: 24,
                    borderRadius: 1,
                    bgcolor: 'text.secondary',
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    flexShrink: 0,
                    mt: 0.25,
                  }}
                >
                  <PersonRounded sx={{ fontSize: 14, color: 'white' }} />
                </Box>
              )}
            </Stack>
          </Fade>
        ))}
        <div ref={messagesEndRef} />
      </Box>

      <Divider />

      {/* Input */}
      <Box sx={{ p: 1.25, display: 'flex', gap: 1, alignItems: 'flex-end' }}>
        <TextField
          multiline
          maxRows={2}
          fullWidth
          size="small"
          placeholder={t('dashboard.widgets.aiChat.placeholder', 'Ask me anything…')}
          value={input}
          onChange={(e) => setInput(e.target.value)}
          onKeyDown={handleKeyDown}
          disabled={isLoading}
          id="ai-chat-widget-input"
          sx={{
            '& .MuiOutlinedInput-root': { borderRadius: 1.5, fontSize: '0.8rem' },
          }}
        />
        <IconButton
          id="ai-chat-widget-send"
          size="small"
          onClick={sendMessage}
          disabled={!input.trim() || isLoading}
          color="primary"
          sx={{
            bgcolor: 'primary.main',
            color: 'white',
            borderRadius: 1.5,
            width: 34,
            height: 34,
            flexShrink: 0,
            '&:hover': { bgcolor: 'primary.dark' },
            '&.Mui-disabled': { bgcolor: 'action.disabledBackground' },
          }}
        >
          {isLoading ? <CircularProgress size={14} color="inherit" /> : <SendRounded sx={{ fontSize: 16 }} />}
        </IconButton>
      </Box>
    </Paper>
  )
}

export default AiChatWidget
