import React from 'react'
import { Box, Paper, Stack, Typography, Chip } from '@mui/material'
import TrendingUpRounded from '@mui/icons-material/TrendingUpRounded'
import TrendingDownRounded from '@mui/icons-material/TrendingDownRounded'
import TrendingFlatRounded from '@mui/icons-material/TrendingFlatRounded'
import PeopleRounded from '@mui/icons-material/PeopleRounded'
import { useTranslation } from 'react-i18next'

interface StatCardWidgetProps {
  label?: string
  value?: string | number
  trend?: 'up' | 'down' | 'flat'
  trendValue?: string
  icon?: 'people' | 'trending'
  color?: 'primary' | 'success' | 'warning' | 'error' | 'info'
}

/**
 * StatCard / KPI Widget
 *
 * A simple Key Performance Indicator card showing a metric with:
 * - A prominent value
 * - A label/title
 * - A trend indicator (up/down/flat) with percentage
 * - An optional icon with colored background
 *
 * Registered in the widget registry as 'dashboard-widget-statCard'.
 * Can be generated by the AI Widget Studio pipeline.
 */
const StatCardWidget: React.FC<StatCardWidgetProps> = ({
  label,
  value,
  trend = 'up',
  trendValue = '+12.5%',
  color = 'primary',
}) => {
  const { t } = useTranslation()

  const displayLabel = label ?? t('dashboard.widgets.statCard.defaultLabel', 'Total Users')
  const displayValue = value ?? '48,295'

  const TrendIcon =
    trend === 'up'
      ? TrendingUpRounded
      : trend === 'down'
      ? TrendingDownRounded
      : TrendingFlatRounded

  const trendColor =
    trend === 'up' ? 'success' : trend === 'down' ? 'error' : 'default'

  return (
    <Paper
      variant="outlined"
      sx={{
        p: 3,
        height: '100%',
        display: 'flex',
        flexDirection: 'column',
        minHeight: 200,
        position: 'relative',
        overflow: 'hidden',
        transition: 'box-shadow 0.2s ease',
        '&:hover': { boxShadow: 4 },
      }}
    >
      {/* Decorative gradient blob */}
      <Box
        sx={{
          position: 'absolute',
          top: -24,
          right: -24,
          width: 80,
          height: 80,
          borderRadius: '50%',
          background: (theme) =>
            `radial-gradient(circle, ${theme.palette[color].main}22 0%, transparent 70%)`,
          pointerEvents: 'none',
        }}
      />

      {/* Icon + Label row */}
      <Stack direction="row" justifyContent="space-between" alignItems="flex-start">
        <Box>
          <Typography variant="body2" color="text.secondary" fontWeight={500}>
            {displayLabel}
          </Typography>
        </Box>
        <Box
          sx={{
            width: 40,
            height: 40,
            borderRadius: 2,
            background: (theme) =>
              `linear-gradient(135deg, ${theme.palette[color].main}cc, ${theme.palette[color].dark ?? theme.palette[color].main})`,
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            boxShadow: (theme) => `0 4px 12px ${theme.palette[color].main}44`,
          }}
        >
          <PeopleRounded sx={{ color: 'white', fontSize: 22 }} />
        </Box>
      </Stack>

      {/* Main value */}
      <Box sx={{ flex: 1, display: 'flex', flexDirection: 'column', justifyContent: 'center' }}>
        <Typography
          variant="h3"
          fontWeight={800}
          sx={{
            lineHeight: 1,
            mt: 1.5,
            background: (theme) =>
              `linear-gradient(135deg, ${theme.palette.text.primary}, ${theme.palette[color].main})`,
            backgroundClip: 'text',
            WebkitBackgroundClip: 'text',
            WebkitTextFillColor: 'transparent',
          }}
        >
          {displayValue}
        </Typography>
      </Box>

      {/* Trend badge */}
      <Stack direction="row" spacing={1} alignItems="center" sx={{ mt: 1.5 }}>
        <Chip
          icon={<TrendIcon sx={{ fontSize: '14px !important' }} />}
          label={trendValue}
          size="small"
          color={trendColor as 'success' | 'error' | 'default'}
          variant="outlined"
          sx={{ fontWeight: 700, fontSize: '0.7rem' }}
        />
        <Typography variant="caption" color="text.disabled">
          vs last period
        </Typography>
      </Stack>
    </Paper>
  )
}

export default StatCardWidget
