export { default as SignUp } from './screens/SignUp'
export { default } from './screens/SignUp'
export { useSignUpFlow } from './hooks/useSignUpFlow'
export * from './components/RegistrationStep'
export * from './components/VerifyEmailStep'
export * from './components/SuccessStep'
export * from './components/LockedStep'

// Backward-compatible exports
export { default as SignUpV2 } from './screens/SignUp'
export { default as CheckEmailConfirmation } from './components/CheckEmailConfirmation'
export { default as EmailVerificationScreen } from './components/EmailVerificationScreen'
export { default as EmailVerifiedSuccess } from './components/EmailVerifiedSuccess'
export { default as RegistrationSuccess } from './components/RegistrationSuccess'
export { default as VerificationLinkExpired } from './components/VerificationLinkExpired'
