// ---------------------------------------------------------------------------
// Canonical path registry for the entire auth module.
// Each sub-module also keeps its own path.ts (scoped to that module's paths).
// This file is the single source of truth used by the central route aggregator
// and exported as `AuthPath` from the package root.
// ---------------------------------------------------------------------------

export const Path = {
  user: {
    overview: '/user/overview',
    view: '/user/:id',
    edit: '/user/:id/edit',
    changeEmail: '/user/change-email',
    changePassword: '/user/change-password',
    delete: '/user/delete',
    deactivate: '/user/deactivate',
    linkedAccounts: '/user/linked-accounts',
    activeSessions: '/user/sessions',
    emailChangeStatus: '/user/email-change-status',
    initiateEmailChange: '/user/initiate-email-change',
    activityTimeline: '/user/activity',
    sessions: '/user/sessions',
    security: '/user/security',
    settings: '/user/settings',
  },
  apiTokens: {
    dashboard: '/auth/api-tokens',
    createBasic: '/auth/api-tokens/create/basic',
    createRestrictions: '/auth/api-tokens/create/restrictions',
    details: '/auth/api-tokens/:tokenId',
    display: '/auth/api-tokens/:tokenId/display',
    actions: '/auth/api-tokens/:tokenId/actions',
    securityWarning: '/auth/api-tokens/security-warning',
  },
  identity: {
    permissionConsent: '/auth/sso/consent',
    oidcLoginPrompt: '/auth/sso/oidc-prompt',
    providerSelection: '/auth/sso/select-provider',
    authWait: '/auth/sso/wait',
    samlMetadataDisplay: '/auth/sso/saml-metadata',
    samlMetadataBrowser: '/auth/sso/saml-browser',
    oidcConfigBrowser: '/auth/sso/oidc-config',
    oidcClientCreate: '/auth/sso/oidc-config/create',
    oidcClientEdit: '/auth/sso/oidc-config/:id/edit',
    samlConfigDashboard: '/auth/sso/saml-config',
    ssfConfiguration: '/auth/sso/ssf-config',
    jwksManagement: '/auth/sso/jwks',
    oidcWait: '/auth/sso/oidc/wait',
    samlWait: '/auth/sso/saml/wait',
    samlSSOInitiation: '/auth/sso/login',
  },
  account: {
    overview: '/auth/account',
    profile: '/auth/account',
    view: '/auth/account/view',
    edit: '/auth/account/edit',
    changeEmail: '/auth/account/change-email',
    changePassword: '/auth/account/change-password',
    delete: '/auth/account/delete',
    deactivate: '/auth/account/deactivate',
    linkedAccounts: '/auth/account/linked-accounts',
    activeSessions: '/auth/account/active-sessions',
    emailChangeStatus: '/auth/account/email-change-status',
    initiateEmailChange: '/auth/account/initiate-email-change',
    activityTimeline: '/auth/account/activity-timeline',
    sessions: '/auth/account/active-sessions',
    security: '/auth/account/security',
    settings: '/auth/account/settings',
  },
  mfa: {
    setup: '/auth/mfa/setup',
    verification: '/auth/mfa/verify',
    backup_codes: '/auth/mfa/backup-codes',
    verification_success: '/auth/mfa/success',
    management: '/auth/mfa/manage',
    dashboard: '/auth/mfa/dashboard',
    backup_entry: '/auth/mfa/backup-entry',
    add_method: '/auth/mfa/add-method',
    security_keys: '/auth/mfa/security-keys',
  },
  passkey: {
    setup: '/auth/passkey/setup',
    management: '/auth/passkey/management',
    recovery: '/auth/passkey/recovery',
    usage_stats: '/auth/passkey/usage-stats',
    creation_options: '/auth/passkey/create',
    login: '/auth/passkey/login',
    naming_config: '/auth/passkey/configure',
    platform_login: '/auth/passkey/platform-login',
    platform_register: '/auth/passkey/platform-register',
  },
  auth: {
    signin: '/auth/sign-in',
    signinV2: '/auth/sign-in-v2',
    login: '/auth/login',
    signup: '/auth/sign-up',
    signupV2: '/auth/sign-up-v2',
    registration: '/auth/register',
    signupSuccess: '/auth/sign-up/success',
    checkEmail: '/auth/verify-email-confirmation',
    verifyEmail: '/auth/verify-email/:email',
    verificationLinkExpired: '/auth/verification-link-expired',
    forgotPassword: '/auth/recovery/forgot-password',
    resetPassword: '/auth/recovery/reset-password',
    setNewPassword: '/auth/recovery/set-new-password/:email',
    passwordResetSuccess: '/auth/recovery/password-reset-success',
    registrationSuccess: '/auth/registration-success',
    emailVerification: '/auth/verification/email-sent',
    emailVerifiedSuccess: '/auth/verify-email/success',
    requestEmailChange: '/auth/email/request-change',
    initiateEmailChange: '/auth/email/initiate-change',
    emailChangeVerificationPending: '/auth/email/change-verification-pending',
    emailChangeVerification: '/auth/email/verify-change/:token',
    emailChangeSuccess: '/auth/email/change-success',
    emailChangeFailed: '/auth/email/change-failed',
    emailChangeStatus: '/auth/email/change-status',
    mfaVerification: '/auth/mfa/verification',
    exportVerification: '/auth/export/verification',
    deviceCode: '/auth/device/code',
    adminLogin: '/auth/admin/login',
    joinOrganization: '/auth/join-organization',
    unauthorized401: '/auth/401',
    maintenance: '/auth/maintenance',
    tooManyRequests429: '/auth/429',
    forbidden403: '/auth/403',
    csrfError: '/auth/csrf-error',
    browserNotSupported: '/auth/browser-not-supported',
    // SSO & Identity Aliases (User-facing only)
    samlWait: '/auth/sso/saml/wait',
    oidcWait: '/auth/sso/oidc/wait',
    providerSelection: '/auth/sso/select-provider',
    permissionConsent: '/auth/sso/consent',
    oidcLoginPrompt: '/auth/sso/oidc-prompt',
  },
  passwordless: {
    setup: '/auth/passwordless/init',
    verification: '/auth/passwordless/verify',
  },
  admin: {
    root: '/admin',
    dashboard: '/admin/dashboard',
    themeEditor: '/admin/theme-editor',
    themeBuilder: '/admin/theme-builder',
    overview: '/admin',
    users: '/admin/users',
    userProfile: '/admin/users/:id',
    banManagement: '/admin/bans',
    impersonationLogs: '/admin/impersonation-logs',
    organizations: '/admin/organizations',
    organizationProfile: '/admin/organizations/:id',
    invitations: '/admin/organizations/:id/invitations',
    roles: '/admin/roles',
    roleDetail: '/admin/roles/:id',
    permissions: '/admin/permissions',
    policies: '/admin/organizations/:id/policies',
    policyCanvas: '/admin/policies/canvas',
    applications: '/admin/applications',

    appDetail: '/admin/applications/:id',
    scopes: '/admin/scopes',
    apiExplorer: '/admin/api-explorer',
    apiTokens: '/admin/api-tokens',
    webhooks: '/admin/webhooks',
    moduleManagement: '/admin/modules',
    provisioning: '/admin/provisioning',
    scim: '/admin/provisioning/scim',
    syncLogs: '/admin/provisioning/logs',
    connectorDetail: '/admin/provisioning/connectors/:id',
    samlMetadataDisplay: '/admin/sso/saml-metadata/:id',
    samlMetadataBrowser: '/admin/sso/saml-metadata',
    oidcConfigBrowser: '/admin/sso/oidc-config',
    oidcClientCreate: '/admin/sso/oidc-config/create',
    oidcClientEdit: '/admin/sso/oidc-config/:id',
    samlConfigDashboard: '/admin/sso/saml-config',
    ssfConfiguration: '/admin/sso/ssf-config',
    jwksManagement: '/admin/sso/jwks',
    events: '/admin/events',
    health: '/admin/health',
    exportAudit: '/admin/export-audit',
  },
  monitoring: {
    emailTesting: '/admin/email-testing',
    emailTemplatePreview: '/admin/email-preview/:id',
    mfa_analytics: '/admin/mfa-analytics',
  },

  // Flat aliases for direct access (backward compatibility and shorthand)
  profile: '/auth/account',
  signin: '/auth/sign-in',
  signinV2: '/auth/sign-in-v2',
  signup: '/auth/sign-up',
  forgotPassword: '/auth/recovery/forgot-password',
  resetPassword: '/auth/recovery/reset-password',
  checkEmail: '/auth/verify-email-confirmation',
  verifyEmail: '/auth/verify-email/:email',
  verificationLinkExpired: '/auth/verification-link-expired',
  registration: '/auth/register',
}


// Flat aliases for direct access (backward compatibility and shorthand)
export const FlatPath = {
  ...Path,
  // Common shorthands used in core screens
  profile: Path.account.overview,
  signin: Path.auth.signin,
  signinV2: Path.auth.signinV2,
  signup: Path.auth.signup,
  forgotPassword: Path.auth.forgotPassword,
  resetPassword: Path.auth.resetPassword,
  checkEmail: Path.auth.checkEmail,
  verifyEmail: Path.auth.verifyEmail,
  verificationLinkExpired: Path.auth.verificationLinkExpired,
  registration: Path.auth.registration,
}

export default Path
