export const AuthPath = {
  account: {
    overview: '/account/overview',
    security: '/account/security',
    preferences: '/account/preferences',
    sessions: '/account/sessions',
    activityTimeline: '/account/activity',
    changePassword: '/account/change-password',
  },
  user: {
    overview: '/user/overview',
    view: '/user/:id',
    edit: '/user/:id/edit',
    changeEmail: '/user/change-email',
    changePassword: '/user/change-password',
    delete: '/user/delete',
    deactivate: '/user/deactivate',
    linkedAccounts: '/user/linked-accounts',
    activeSessions: '/user/sessions',
    emailChangeStatus: '/user/email-change-status',
    initiateEmailChange: '/user/initiate-email-change',
    activityTimeline: '/user/activity',
    sessions: '/user/sessions',
    security: '/user/security',
    settings: '/user/settings',
  },
  apiTokens: {
    dashboard: '/auth/api-tokens',
    createBasic: '/auth/api-tokens/create/basic',
    createRestrictions: '/auth/api-tokens/create/restrictions',
    details: '/auth/api-tokens/:tokenId',
    display: '/auth/api-tokens/:tokenId/display',
    actions: '/auth/api-tokens/:tokenId/actions',
    securityWarning: '/auth/api-tokens/security-warning',
  },
  identity: {
    permissionConsent: '/auth/sso/consent',
    oidcLoginPrompt: '/auth/sso/oidc-prompt',
    providerSelection: '/auth/sso/select-provider',
    authWait: '/auth/sso/wait',
    samlMetadataDisplay: '/auth/sso/saml-metadata',
    samlMetadataBrowser: '/auth/sso/saml-browser',
    oidcConfigBrowser: '/auth/sso/oidc-config',
    oidcClientCreate: '/auth/sso/oidc-config/create',
    oidcClientEdit: '/auth/sso/oidc-config/:id/edit',
    samlConfigDashboard: '/auth/sso/saml-config',
    ssfConfiguration: '/auth/sso/ssf-config',
    jwksManagement: '/auth/sso/jwks',
    oidcWait: '/auth/sso/oidc/wait',
    samlWait: '/auth/sso/saml/wait',
    samlSSOInitiation: '/auth/sso/login',
    oidcSSOInitiation: '/auth/sso/oidc/login',
    oidcSSORegistration: '/auth/sso/oidc/register',
  },
  session: {
    sessions: '/auth/sessions',
    view: '/auth/sessions/:id',
    revoke: '/auth/sessions/:id/revoke',
    revokeAll: '/auth/sessions/revoke-all',
    mfa: '/auth/sessions/mfa',
    trustedDevices: '/auth/sessions/trusted-devices',
    deviceManagement: '/auth/sessions/devices',
    deviceRevoke: '/auth/sessions/devices/:id/revoke',
  },
  mfa: {
    root: '/auth/mfa',
    setup: '/auth/mfa/setup',
    verify: '/auth/mfa/verify',
    backupCodes: '/auth/mfa/backup-codes',
    selectMethod: '/auth/mfa/select-method',
    authenticator: '/auth/mfa/authenticator',
    email: '/auth/mfa/email',
    sms: '/auth/mfa/sms',
    totp: '/auth/mfa/totp',
    passkey: '/auth/mfa/passkey',
    recovery: '/auth/mfa/recovery',
  },
  passkey: {
    setup: '/auth/passkey/setup',
    management: '/auth/passkey/management',
    recovery: '/auth/passkey/recovery',
    usage_stats: '/auth/passkey/usage-stats',
    creation_options: '/auth/passkey/create',
    login: '/auth/passkey/login',
    naming_config: '/auth/passkey/configure',
    platform_login: '/auth/passkey/platform-login',
    platform_register: '/auth/passkey/platform-register',
  },
  passwordless: {
    setup: '/auth/passwordless/init',
    verification: '/auth/passwordless/verify',
  },
  auth: {
    unauthorized401: '/auth/unauthorized',
    maintenance: '/auth/maintenance',
    tooManyRequests429: '/auth/too-many-requests',
    csrfError: '/auth/csrf-error',
    browserNotSupported: '/auth/browser-not-supported',
    forbidden403: '/auth/forbidden',
  },
  password: {
    forgot: '/auth/password/forgot',
    reset: '/auth/password/reset',
    update: '/auth/password/update',
    expired: '/auth/password/expired',
  },
  login: {
    root: '/auth/login',
    callback: '/auth/login/callback',
    sso: '/auth/login/sso',
    magic: '/auth/login/magic',
  },
  register: {
    root: '/auth/register',
    verify: '/auth/register/verify',
    complete: '/auth/register/complete',
  },
  verification: {
    email: '/auth/verification/email',
    phone: '/auth/verification/phone',
  },
  admin: {
    root: '/admin',
    dashboard: '/admin/dashboard',
    themeEditor: '/admin/theme-editor',
    themeBuilder: '/admin/theme-builder',
    overview: '/admin',
    users: '/admin/users',
    userProfile: '/admin/users/:id',
    banManagement: '/admin/bans',
    impersonationLogs: '/admin/impersonation-logs',
    organizations: '/admin/organizations',
    organizationProfile: '/admin/organizations/:id',
    invitations: '/admin/organizations/:id/invitations',
    roles: '/admin/roles',
    roleDetail: '/admin/roles/:id',
    permissions: '/admin/permissions',
    policies: '/admin/organizations/:id/policies',
    applications: '/admin/applications',
    appDetail: '/admin/applications/:id',
    scopes: '/admin/scopes',
    apiExplorer: '/admin/api-explorer',
    apiTokens: '/admin/api-tokens',
    webhooks: '/admin/webhooks',
    provisioning: '/admin/provisioning',
    scim: '/admin/provisioning/scim',
    syncLogs: '/admin/provisioning/logs',
    connectorDetail: '/admin/provisioning/connectors/:id',
    samlMetadataDisplay: '/admin/sso/saml-metadata/:id',
    samlMetadataBrowser: '/admin/sso/saml-metadata',
    oidcConfigBrowser: '/admin/sso/oidc-config',
    oidcClientCreate: '/admin/sso/oidc-config/create',
    oidcClientEdit: '/admin/sso/oidc-config/:id',
    samlConfigDashboard: '/admin/sso/saml-config',
    ssfConfiguration: '/admin/sso/ssf-config',
    jwksManagement: '/admin/sso/jwks',
    events: '/admin/events',
    health: '/admin/health',
    exportAudit: '/admin/export-audit',
  },
  monitoring: {
    root: '/auth/monitoring',
    health: '/auth/monitoring/health',
    metrics: '/auth/monitoring/metrics',
    audit: '/auth/monitoring/audit',
  },
}

export const FlatPath = {
  ...AuthPath.user,
  ...AuthPath.apiTokens,
  ...AuthPath.identity,
  ...AuthPath.session,
  ...AuthPath.mfa,
  ...AuthPath.password,
  ...AuthPath.login,
  ...AuthPath.register,
  ...AuthPath.verification,
  ...AuthPath.admin,
  ...AuthPath.monitoring,
}

export default AuthPath
