export { default as DeactivateAccount } from './DeactivateAccount'
export { default as DeleteAccount } from './DeleteAccount'
export { default as ChangeEmail } from './ChangeEmail'
export { DataExport } from './DataExport'
export { default as PrivacyCenter } from './PrivacyCenter'
export { default as ErasureConfirmation } from './ErasureConfirmation'
