/// <reference types="vite/client" />
import './types/pwa.d.ts'
import './types/mui.d.ts'

export * from '@cap/platform-store'
export { AdaptiveLogo, Alert, Copyright } from '@cap/theme'

export { default as defaultCoreTheme } from './theme'
export type { Settings } from '@cap/shared-types'
export * from './types'
export * from './services'
export * from './i18n/i18n'
export * from './i18n/registry'
export { themeConfig } from '@cap/theme'

export * from './utils'
export * from './assembly'
export { default as useObjectCookie } from './hooks/useObjectCookie'
export * from './hooks/usePermissions'
export * from './contexts/tenantContext'
export * from './contexts/LayoutEngineContext'
export * from './hooks/useDynamicTheme'
export * from './hooks/useNetworkSync'
export * from './hooks/useAuth'
export * from './hooks/useNavigation'
export * from './hooks/useResizeObserver'
export * from './hooks/useContainerQuery'
export * from './contexts/ContainerSizeContext'
export * from './components'

export * from './registry/PluginRegistry'
export * from './registry/WidgetRegistry'
export * from './authorization/bootstrap'
