const Path = {
  permissionConsent: '/auth/sso/consent',
  oidcLoginPrompt: '/auth/sso/oidc-prompt',
  providerSelection: '/auth/sso/select-provider',
  authWait: '/auth/sso/wait',
  samlMetadataDisplay: '/auth/sso/saml-metadata',
  samlMetadataBrowser: '/auth/sso/saml-browser',
  oidcConfigBrowser: '/auth/sso/oidc-config',
  oidcClientCreate: '/auth/sso/oidc-config/create',
  oidcClientEdit: '/auth/sso/oidc-config/:id/edit',
  samlConfigDashboard: '/auth/sso/saml-config',
  ssfConfiguration: '/auth/sso/ssf-config',
  jwksManagement: '/auth/sso/jwks',
  oidcWait: '/auth/sso/oidc/wait',
  samlWait: '/auth/sso/saml/wait',
  samlSSOInitiation: '/auth/sso/login',
  provisioning: '/admin/provisioning',
  scim: '/admin/provisioning/scim',
  syncLogs: '/admin/provisioning/logs',
  connectorDetail: '/admin/provisioning/connectors/:id',
}
export default Path
